name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
      
    - name: Install toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1
    - run: arm-none-eabi-gcc --version

    - name: Create project files
      run: make check && make
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: bin/


